version: '3.8'

services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER:?}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?}
      POSTGRES_DB: ${DATABASE_NAME:?}
    ports:
      - ${DATABASE_PORT:?}:5432
    # volumes: ASK MO about the volumes
    #   - ./backend/data:var/lib/postgresql
    restart: always
    container_name: postgres
  
  backend:
    image: music-api/backend
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=${DATABASE_USER:?}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?}
      - DATABASE_NAME=${DATABASE_NAME:?}
      - DATABASE_PORT=${DATABASE_PORT:?}
    ports:
      - ${BACKEND_PORT:?}:3000
      - 5556:5555
    container_name: backend

  frontend:
    image: music-api/frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT:?}:3000
    container_name: frontend
